title: Lutfil

logo: /assets/img/kowalski.PNG

description: Senior Lecturer | AI & Data Analytics in Energy | Smart Grid & Renewable Energy Solutions  

#show_downloads: true

theme: jekyll-theme-minimal
